services:
  bot-guard:
    container_name: Server-guard
    image: ghcr.io/fsnova/server-guard-bot:latest
    environment:
      - TZ=Asia/Tehran
    build: .
    env_file: .env
    volumes:
      - ./data:/data
    restart: unless-stopped